### ISSUE TITLE
v2.2.6 - Thousands separator does not appear for Rat Shillings (and maybe KhanKoinz)

### ISSUE THREAD

**Issue by ZolanaPrime** [lensvol/fl-small-mercies#11]
v2.2.6 - If you have >1,000 rat shillings, the comma separator does not appear. Untested with Khaganian Coinage, but issue may be there too)

**Comment by lensvol** [comment]
Yes, it is a known issue and had been fixed in https://github.com/lensvol/fl-small-mercies/commit/29639c72bb1c5f10350557dc71a75f9af904d412.

Should ship with the next major version :)

**Comment by ZolanaPrime** [comment]
That's brilliant - thanks!

Marking as closed :)
