### ISSUE TITLE
Quick storylet saving uses "Hello, world!" as title for every journal entry.

### ISSUE THREAD

**Issue by Maddremor** [lensvol/fl-small-mercies#13]
When saving a journal entry without the addon the user has the option of writing their own title for the enty, but the title defaults to that shown in the game. The addon seems to give the default string of "Hello, world!" for everything. As an example, see [this entry](https://www.fallenlondon.com/profile/Maddremor/34135479) or anything surrounding it.

**Comment by lensvol** [comment]
That is certainly sub-optimal, hopefully I will be able to take a look soon.

**Comment by lensvol** [comment]
Fixed in version 3.0.1
