### ISSUE TITLE
Bug: Extension not respecting currencies setting

### ISSUE THREAD

**Issue by umbralOptimatum** [lensvol/fl-small-mercies#17]
I have show additional currencies disabled, but when I enter the Tracklayers' City or do anything there, the Hinterland Prosperity display appears in the sidebar.

**Comment by lensvol** [comment]
Yes, the new indicator has some issues in regard to its activation. I will soon release a bugfix release, stay tuned.

**Comment by lensvol** [comment]
*sigh* I really need to up my testing game... Will fix it soon.

Each subsetting seems like a good idea, but the current layout of the "Preferences" screen seems ill-suited for that. Maybe after a rework?
