### ISSUE TITLE
Two-step confirmation is broken

### ISSUE THREAD

**Issue by fynngodau** [lensvol/fl-small-mercies#20]
Since https://github.com/lensvol/fl-small-mercies/commit/6f864e452710cb687861efd41a6ad9c497e3190a, the "YES!" storylet in the _Book of Wick_ two step confirmation fake storylet doesn't work anymore. The reason is that the modified request that is caused by the click on the fake confirmation branch – where the fake branch ID (original + `FAKE_BRANCH_ID_THRESHOLD`) needs to be replaced with the original – is no longer propagated to the caller.

* Modified request:
https://github.com/lensvol/fl-small-mercies/blob/f54fd47a17b6a64095f384a66b641c07230dfb70/src/fixers/two_step_confirmations.ts#L173-L176
* Not propagated to caller here (due to the structured clone in line 125): https://github.com/lensvol/fl-small-mercies/blob/f54fd47a17b6a64095f384a66b641c07230dfb70/src/api_interceptor.ts#L123-L133

**Comment by lensvol** [comment]
Oof, this is a bad one. I am sorry for not reacting to this earlier, I was on vacation and missed the notification :(

Will fix it ASAP.

**Comment by fynngodau** [comment]
No problem. I hope you had a nice vacation :heart:
