### ISSUE TITLE
Missing Vanities to add to vanity_section.ts

### ISSUE THREAD

**Issue by ZolanaPrime** [lensvol/fl-small-mercies#23]
New 777:

`    [777, 145263], // An Interloper in the Library`

New section for the three 77s:

`    [77, 144494], // A Shaper of Starved Culture`
`    [77, 144203], // Neighbourhood Noctivagant`
`    [77, 144910], // Volatile Consignments Delivered to the Remote Magazine`

**Comment by lensvol** [comment]
Thank you! Added in d47d305b210935f589199706a599e94b9d748a16
