### ISSUE TITLE
Stuiver icon not appearing

### ISSUE THREAD

**Issue by RhialtoTheMarvellous** [lensvol/fl-small-mercies#27]
It looks like there's a typo in extension.css: this should be `.currency__stuiver`, not `.currency__stuivers`.

https://github.com/lensvol/fl-small-mercies/blob/04a408696990c8073f51092c40bd4ae7f4a3cdb8/src/css/extension.css#L85

---

On a related note, I made my own icon based on the in-game graphic. Is that something you'd want to include in future versions?

![Screenshot 2024-09-19 182656](https://github.com/user-attachments/assets/3889d521-753e-47de-9f0f-a0d015ac9375)

**Comment by lensvol** [comment]
Good catch! Thank you, I will release a patched version soon.

The custom icon looks somewhat out of place with the current set. However, I am looking into adding a capability to replace specific pieces of artwork as an option for further major releases.

**Comment by lensvol** [comment]
@RhialtoTheMarvellous Solved in 254875f181ed0da070840deefcbb01513ae29963.
