### ISSUE TITLE
Action Locking Button

### ISSUE THREAD

**Issue by Phauks** [lensvol/fl-small-mercies#7]
I really enjoy how you made a lock for the Ship-selling action so that players don't accidently go through with that action.

Could you make it so a button appeared next to potential actions that enabled us to lock certain actions we never want to participate in? There are certain actions as a player I don't want to accidently partake in, but I understand that these specific actions will be different for each player. By putting the power to the user, it makes it very tailorable to the individual experience.

**Comment by lensvol** [comment]
While there are plans to implement two-step "confirmation" for dangerous storylets, I believe the requested functionality is already covered by the "Playing Favourites" extension.
